### ISSUE TITLE
Fedy fails to install Idea Community/ Ultimate

### ISSUE THREAD

**Issue by nmehta001** [folkswithhats/fedy-plugins-developers#13]
IDEA has updated and I believe that the update has broken the code used to install IDEA via fedy

EDIT:
Wanted to confirm that it is the update, I set up a new Fedora install on a VM and it fails to install. The problem persists with many of the intellij products such as RubyMine etc

**Comment by DStewart1997** [comment]
Also having this issue, looking into it, looks like a simple link change, will make a PR.

**Comment by DStewart1997** [comment]
Looks like the source for the website has changed. The old method downloaded the source of the download page and used grep to find the direct download link for the tar.gz.

I assume it got the link from the "Your download should start shortly. If it doesn't, please use direct link."
But here is the source from that text:
```
<p class="sub-title">
    Your download should start shortly. If it doesn't, please use <a data-release-download-link="">direct link</a>.
</p>
```

I'm not sure how to get the download link using this method.

**Comment by nmehta001** [comment]
I attempted to have a look at the direct link by right clicking it:
https://download.jetbrains.com/idea/ideaIC-15.0.2.tar.gz

It's slightly different to the new link change:
https://www.jetbrains.com/idea/download/download-thanks.html?code=IIC

**Comment by DStewart1997** [comment]
Yeah, the main link has changed - what the script does is it greps the source of that web page for the tar.gz link that you have mentioned - but the source no longer mentions the tar.gz link.

When you go to that page you see a block of text "Your download should start shortly. If it doesn't, please use direct link." and you can click the "direct link" part to start the download - this directs to the tar.gz url.

So the old web page likely had this code behind it (or something similar):
```
<p class="sub-title">
    Your download should start shortly. If it doesn't, please use <a href="https://download.jetbrains.com/idea/ideaIC-15.0.2.tar.gz">direct link</a>.
</p>
```

Whereas now it has:
```
<p class="sub-title">
    Your download should start shortly. If it doesn't, please use <a data-release-download-link="">direct link</a>.
</p>
````

So the direct tar.gz link is not in the source code for the web page anymore - so another method has to be used. Do you understand what I mean?

**Comment by nmehta001** [comment]
I understand what you mean, it could be easier to remove the grep part and then download without it. I'll do a bit of testing before hand and then see if I can come up with a solution

**Comment by DStewart1997** [comment]
You need the grep to match the version number - unless you hard code the version number and update the plugin each time (which is quite a bit of hassle).

    /ideaIC-[0-9.]*.tar.gz"

**Comment by user501254** [comment]
I think the contents like link to the `tar.gz` package and version string on the download page is now loaded through AJAX request. It's a wild guess though and I might be wrong.

**Comment by nmehta001** [comment]
Thanks! Your fix works, I hope you don't mind but I took it and applied the link to Ultimate accordingly, gave you credit

**Comment by user501254** [comment]
You're welcome.
