### ISSUE TITLE
Add Arduino

### ISSUE THREAD

**Issue by bil-elmoussaoui** [folkswithhats/fedy-plugins-developers#14]

**Comment by user501254** [comment]
Isn't that available in the official Fedora repos?

    [ashesh@MISTRI ~] $ dnf search arduino
    Last metadata expiration check performed 0:01:01 ago on Tue Dec 15 14:47:14 2015.
    =============================================== N/S Matched: arduino ===============================================
    arduino.noarch : An IDE for Arduino-compatible electronics prototyping platforms
    eclipse-cdt-arduino.x86_64 : Arduino C++ Tools
    arduino-doc.noarch : Documentation for the Arduino micro-controller platform
    arduino-core.noarch : Files required for compiling code for Arduino-compatible micro-controllers
    ino.noarch : Command line toolkit for working with Arduino hardware

**Comment by bil-elmoussaoui** [comment]
This version is outdated :/ the latest version is 1.6.6

**Comment by user501254** [comment]
Okay, there's a pending pull request.

**Comment by Abhinav1217** [comment]
@bil-elmoussaoui  I have merged the plugin. But won't be bundling with the release for now.  You can download the plugin from this repo and put the `arduino.plugin` folder in `~/.local/share/fedy/plugins` folder for fedy to use.

Improved plugin experience is planned. Can't comment on the timeline at present.
