### ISSUE TITLE
Unity3D Editor

### ISSUE THREAD

**Issue by bil-elmoussaoui** [folkswithhats/fedy-plugins-developers#20]
Add Unity3D Editor. 
There's a bash script to install the editor but there's some missing dependencies like `libpq.so.5`. And the desktop file is not created automatically.. Something worth to be added to Fedy Developers plugins ;)

**Comment by Abhinav1217** [comment]
We shall look into it.  A pull request would be welcome.

**Comment by DStewart1997** [comment]
Here's a link to the forum post regarding Unity on Linux.
It includes a breakdown of all the dependencies too, will have a look into it but will leave the link here for anyone else interested in creating the installer.

http://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by Abhinav1217** [comment]
Thanks for the link. @DStewart1997 . It would be great help.

**Comment by bddenhartog** [comment]
This repository is being deprecated, as the plugins have been merged into Fedy core: https://github.com/folkswithhats/fedy

This issue has been recreated in the `folkswithhats/fedy` repository: folkswithhats/fedy#420
