### ISSUE TITLE
Obsolete plugins?

### ISSUE THREAD

**Issue by user501254** [folkswithhats/fedy-plugins-developers#5]
I was able to install Eclipse and Zeal from the official Repositories via `dnf install ...`, is there a reason for still having them as plugin in Fedy?

Eclipse (and related) - https://admin.fedoraproject.org/pkgdb/packages/eclipse%2A/
Zeal - https://admin.fedoraproject.org/pkgdb/package/zeal/

**Comment by satya164** [comment]
@Abhinav1217 We should remove these.

**Comment by satya164** [comment]
@user501254 A pull request will be awesome.

**Comment by user501254** [comment]
Alright working on it.

**Comment by satya164** [comment]
@user501254 Awesome.

**Comment by user501254** [comment]
@satya164 

I am not totally sure if alternatives to these are present in the Fedora repos.

- eclipseautomotive
- eclipsedsl
- eclipsemodeling
- eclipsercp
- eclipsereporting
- eclipsescout
- eclipsetesting
- eclipsestandard

However I guess one can first install eclipse through `sudo -c "dnf intsall eclipse"` and then use the built in "Install New Software wizard"  to get them so they may be removed from Fedy as well. 

But in case I am wrong, and that can not be done through Install New Software wizard, I think it would be better to keep all eclipse related stuff in Fedy, just to maintain consistency. Your call. 

See: https://github.com/folkswithhats/fedy-plugins-developers/pull/11, https://github.com/folkswithhats/fedy-plugins-developers/pull/10, https://github.com/folkswithhats/fedy-plugins-developers/pull/9, https://github.com/folkswithhats/fedy-plugins-developers/pull/8, https://github.com/folkswithhats/fedy-plugins-developers/pull/7, https://github.com/folkswithhats/fedy-plugins-developers/pull/6

**Comment by Abhinav1217** [comment]
Zeal was asked here so i bundled it in last update, It wasn't bundled before that.  I haven't bundled eclipses, Not all plugins listed here is bundle with the release. They are just here if someone wants it, they can download it.  I haven't been able to find time to work on community plugin site this month. But I would again work on it next week.  

I don't have plans to bundle eclipse with fedy release but lets not remove them from listing here in case some one wants it.  At least for some more time.  
@user501254 Before removing it, Can  you send a PR with updated installation and un-installation script. This way, Even when we remove them from listing, an updated plugin would be available in github history.  What do you think about this @satya164  .

**Comment by satya164** [comment]
@Abhinav1217 Sure.

**Comment by user501254** [comment]
@Abhinav1217 do you mean a PR with installation & uninstallation script using the `dnf` command (for eclipse and zeal)?

**Comment by Abhinav1217** [comment]
Closing this as it is not an issue.  I will be removing zeal from the listing but no need to remove eclipse for now. It really don't make any difference as we would not be bundling it with fedy release.
